version: '2'
services:
  base:
    image: node:10
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
  install:
    extends:
      service: base
    command: npm install
    command: npm install --prefix client
  build:
    extends:
      service: base
    command: npm run build
