export const AUTH_MOCK_DATA = {
  isAuthenticated: true,
  user: {
    id: "123456789012345678901234",
    name: "Test Person",
    iat: null,
    exp: null,
    budgets: {},
    categoryMap: {},
  },
  loading: false,
  budgets: {
    Food: 200,
    Debt: 50,
    Transportation: 20,
    Entertainment: 10,
    Personal: 100,
  },
  expenseBudgetSum: 380,
  categoryMap: {
    "Food and Drink": "Groceries",
    Shops: "Shopping",
    Travel: "Travel",
    Recreation: "Entertainment",
  },
};
// NOTE THAT I'VE ADDED EXTRA MOCK DATA FOR
// categoriesThisSpendRange, spendingByCategory, incomeSum, and spendingSum
// (because it could be a different time period)
export const PLAID_MOCK_DATA = {
  accounts: [
    {
      _id: "5f463ad8516e210bc63abece",
      userId: "google-oauth2|105271710635022631997",
      itemId: "opQp5nVm7yUowrAPe6L1iJBpJzWz7JiopxMqQ",
      institutionId: "ins_6",
      institutionName: "US Bank",
      __v: 0,
    },
    {
      _id: "5f46de58a4441204a56d2039",
      userId: "google-oauth2|105271710635022631997",
      itemId: "NxNQP1RNo5uoQgRqjqqNtwnJXJ38axTyjJ9wA",
      institutionId: "ins_13",
      institutionName: "PNC",
      __v: 0,
    },
  ],
  transactions: [
    {
      accountName: "PNC",
      transactions: [
        {
          account_id: "RNMLGg8MW5frvGZMlMMbFD8R1vW1wRuRjAKxw",
          account_owner: null,
          amount: -6.33,
          authorized_date: null,
          category: ["Transportation", "Taxi"],
          category_id: "22016000",
          date: "2020-08-26",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Uber",
          name: "Uber 072515 SF**POOL**",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "EyKx349Kj5SjlZ4rRrrzhN43bAveWjuXbJEaQ",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Travel", "Taxi"],
          waiwai_categories: ["Transportation", "Taxi"],
        },
        {
          account_id: "Dmq3Ba8qP5tP9aAQwQQ8iMaGpJBpjGSveJglG",
          account_owner: null,
          amount: -500,
          authorized_date: null,
          category: ["Food", "Restaurants"],
          category_id: "13005000",
          date: "2020-08-23",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Tectra Inc",
          name: "Tectra Inc",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "RNMLGg8MW5frvGZMlMMbFD8KaZVyRbFR83G6X",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Food and Drink", "Restaurants"],
          waiwai_categories: ["Food", "Restaurants"],
        },
        {
          account_id: "Dmq3Ba8qP5tP9aAQwQQ8iMaGpJBpjGSveJglG",
          account_owner: null,
          amount: -2078.5,
          authorized_date: null,
          category: ["Debt", ""],
          category_id: "16000000",
          date: "2020-08-22",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: null,
          name: "AUTOMATIC PAYMENT - THANK",
          payment_channel: "other",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "Dmq3Ba8qP5tP9aAQwQQ8iMakxA3mGXtvbxXA7",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Payment"],
          waiwai_categories: ["Debt", ""],
        },
        {
          account_id: "Dmq3Ba8qP5tP9aAQwQQ8iMaGpJBpjGSveJglG",
          account_owner: null,
          amount: -500,
          authorized_date: null,
          category: ["Food", "Restaurants"],
          category_id: "13005032",
          date: "2020-08-22",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "KFC",
          name: "KFC",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "XZGlrn8Gy5CmzK31W11XtzVRj3dmZLCdGqx7y",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Food and Drink", "Restaurants", "Fast Food"],
          waiwai_categories: ["Food", "Restaurants"],
        },
        {
          account_id: "Dmq3Ba8qP5tP9aAQwQQ8iMaGpJBpjGSveJglG",
          account_owner: null,
          amount: -500,
          authorized_date: null,
          category: ["Personal", "Sporting Goods"],
          category_id: "19046000",
          date: "2020-08-22",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Madison Bicycle Shop",
          name: "Madison Bicycle Shop",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "6Z6MvWg6R8C8my1KqKKjhPo1Mqjagktg4LxEx",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Shops", "Sporting Goods"],
          waiwai_categories: ["Personal", "Sporting Goods"],
        },
        {
          account_id: "6Z6MvWg6R8C8my1KqKKjhPogJ6AJygugJeWaz",
          account_owner: null,
          amount: -25,
          authorized_date: null,
          category: ["Debt", "Credit Card"],
          category_id: "16001000",
          date: "2020-08-13",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: null,
          name: "CREDIT CARD 3333 PAYMENT *//",
          payment_channel: "other",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "yQKxrlVKGeipaZrokooxF1B4naXE7oTyxeDJy",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Payment", "Credit Card"],
          waiwai_categories: ["Debt", "Credit Card"],
        },
        {
          account_id: "RNMLGg8MW5frvGZMlMMbFD8R1vW1wRuRjAKxw",
          account_owner: null,
          amount: -5.4,
          authorized_date: null,
          category: ["Transportation", "Taxi"],
          category_id: "22016000",
          date: "2020-08-13",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Uber",
          name: "Uber 063015 SF**POOL**",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "WQMEkGRMm5idgeMw9wwrhZJx4jz5GXulgK4d8",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Travel", "Taxi"],
          waiwai_categories: ["Transportation", "Taxi"],
        },
        {
          account_id: "VeL8qAWLb5Fn1NZlmllKTewlA1bAJltWkE45A",
          account_owner: null,
          amount: -5850,
          authorized_date: null,
          category: ["Personal", "Debit"],
          category_id: "21006000",
          date: "2020-08-12",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: null,
          name: "ACH Electronic CreditGUSTO PAY 123456",
          payment_channel: "other",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: "ACH",
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "5QbZ5Eobvgikz19qZqqau1Pn5lXaGbTZ9Mpaj",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Transfer", "Debit"],
          waiwai_categories: ["Personal", "Debit"],
        },
        {
          account_id: "XZGlrn8Gy5CmzK31W11XtzVZlyNlqZidgL4MJ",
          account_owner: null,
          amount: -1000,
          authorized_date: null,
          category: ["Income", "Deposit"],
          category_id: "21007000",
          date: "2020-08-12",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: null,
          name: "CD DEPOSIT .INITIAL.",
          payment_channel: "other",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "vjDzlVqDEPi75D38B88ztmygA5k17dsWrAXLv",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Transfer", "Deposit"],
          waiwai_categories: ["Income", "Deposit"],
        },
        {
          account_id: "Dmq3Ba8qP5tP9aAQwQQ8iMaGpJBpjGSveJglG",
          account_owner: null,
          amount: -78.5,
          authorized_date: null,
          category: ["Entertainment", "Gyms and Fitness Centers"],
          category_id: "17018000",
          date: "2020-08-11",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Touchstone",
          name: "Touchstone Climbing",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "VeL8qAWLb5Fn1NZlmllKTew5dZ36lWiWzenjD",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Recreation", "Gyms and Fitness Centers"],
          waiwai_categories: ["Entertainment", "Gyms and Fitness Centers"],
        },
        {
          account_id: "RNMLGg8MW5frvGZMlMMbFD8R1vW1wRuRjAKxw",
          account_owner: null,
          amount: 500,
          authorized_date: null,
          category: ["Transportation", "Airlines and Aviation Services"],
          category_id: "22001000",
          date: "2020-08-11",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "United Airlines",
          name: "United Airlines",
          payment_channel: "other",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "AGVrK3nVaRTaVgPjRjjqtmxoRPb6Wgs1zEobm",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Travel", "Airlines and Aviation Services"],
          waiwai_categories: [
            "Transportation",
            "Airlines and Aviation Services",
          ],
        },
        {
          account_id: "RNMLGg8MW5frvGZMlMMbFD8R1vW1wRuRjAKxw",
          account_owner: null,
          amount: -12,
          authorized_date: null,
          category: ["Food", "Restaurants"],
          category_id: "13005032",
          date: "2020-08-10",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: "3322",
            zip: null,
          },
          merchant_name: "McDonald's",
          name: "McDonald's",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "GlzadPQze5iemkW3B33oudnEz6WmAXf1kynVL",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Food and Drink", "Restaurants", "Fast Food"],
          waiwai_categories: ["Food", "Restaurants"],
        },
        {
          account_id: "RNMLGg8MW5frvGZMlMMbFD8R1vW1wRuRjAKxw",
          account_owner: null,
          amount: -4.33,
          authorized_date: null,
          category: ["Food", "Restaurants"],
          category_id: "13005043",
          date: "2020-08-10",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Starbucks",
          name: "Starbucks",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "nkDoAV5DZzcboBJwmww3Swz58vWy69C6vwGa7",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Food and Drink", "Restaurants", "Coffee Shop"],
          waiwai_categories: ["Food", "Restaurants"],
        },
        {
          account_id: "RNMLGg8MW5frvGZMlMMbFD8R1vW1wRuRjAKxw",
          account_owner: null,
          amount: -89.4,
          authorized_date: null,
          category: ["Food", "Restaurants"],
          category_id: "13005000",
          date: "2020-08-09",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Sparkfun",
          name: "SparkFun",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "bAX4yVxXBJS1RM8DvDDxupmaL6G85WuV8Q3Rg",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Food and Drink", "Restaurants"],
          waiwai_categories: ["Food", "Restaurants"],
        },
        {
          account_id: "6Z6MvWg6R8C8my1KqKKjhPogJ6AJygugJeWaz",
          account_owner: null,
          amount: 4.22,
          authorized_date: null,
          category: ["Income", "Credit"],
          category_id: "21005000",
          date: "2020-08-08",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: null,
          name: "INTRST PYMNT",
          payment_channel: "other",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "9L7p6n87qAuqvEZBQBBjF6Br1zobnqFRjaE74",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Transfer", "Credit"],
          waiwai_categories: ["Income", "Credit"],
        },
        {
          account_id: "Dmq3Ba8qP5tP9aAQwQQ8iMaGpJBpjGSveJglG",
          account_owner: null,
          amount: -500,
          authorized_date: null,
          category: ["Transportation", "Airlines and Aviation Services"],
          category_id: "22001000",
          date: "2020-07-29",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "United Airlines",
          name: "United Airlines",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "w7lBqVKlWjTQ963eXeeWfzGdlrE1gvCrJjl4M",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Travel", "Airlines and Aviation Services"],
          waiwai_categories: [
            "Transportation",
            "Airlines and Aviation Services",
          ],
        },
        {
          account_id: "RNMLGg8MW5frvGZMlMMbFD8R1vW1wRuRjAKxw",
          account_owner: null,
          amount: -6.33,
          authorized_date: null,
          category: ["Transportation", "Taxi"],
          category_id: "22016000",
          date: "2020-07-27",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Uber",
          name: "Uber 072515 SF**POOL**",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "mzDpAV5DQktbG5jg9ggQSewrqRybo8iL6zAG7",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Travel", "Taxi"],
          waiwai_categories: ["Transportation", "Taxi"],
        },
      ],
    },
    {
      accountName: "US Bank",
      transactions: [
        {
          account_id: "W6V6RDGy9ksGE5KDNaJvfDwgK753ywflre46b",
          account_owner: null,
          amount: -6.33,
          authorized_date: null,
          category: ["Transportation", "Taxi"],
          category_id: "22016000",
          date: "2020-08-26",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Uber",
          name: "Uber 072515 SF**POOL**",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "1X5XlEpMaWTd8qjM9JlkI1pV3Ln8jxf5g6mp3",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Travel", "Taxi"],
          waiwai_categories: ["Transportation", "Taxi"],
        },
        {
          account_id: "nLeL5nVQjAsx6Kr9ZDWAiB7MPlyEZ7C6d1GAR",
          account_owner: null,
          amount: -500,
          authorized_date: null,
          category: ["Food", "Restaurants"],
          category_id: "13005000",
          date: "2020-08-23",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Tectra Inc",
          name: "Tectra Inc",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "nLeL5nVQjAsx6Kr9ZDWAiB71mwAVjEi6d1GAx",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Food and Drink", "Restaurants"],
          waiwai_categories: ["Food", "Restaurants"],
        },
        {
          account_id: "nLeL5nVQjAsx6Kr9ZDWAiB7MPlyEZ7C6d1GAR",
          account_owner: null,
          amount: -2078.5,
          authorized_date: null,
          category: ["Debt", ""],
          category_id: "16000000",
          date: "2020-08-22",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: null,
          name: "AUTOMATIC PAYMENT - THANK",
          payment_channel: "other",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "ymymVnlWprtgXjzRdyWqiQpMl1RNzdUy9VDKx",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Payment"],
          waiwai_categories: ["Debt", ""],
        },
        {
          account_id: "nLeL5nVQjAsx6Kr9ZDWAiB7MPlyEZ7C6d1GAR",
          account_owner: null,
          amount: -500,
          authorized_date: null,
          category: ["Food", "Restaurants"],
          category_id: "13005032",
          date: "2020-08-22",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "KFC",
          name: "KFC",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "m1715nVXPAiBDqKx8MVXS5KL9e7pDNULbBA4x",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Food and Drink", "Restaurants", "Fast Food"],
          waiwai_categories: ["Food", "Restaurants"],
        },
        {
          account_id: "nLeL5nVQjAsx6Kr9ZDWAiB7MPlyEZ7C6d1GAR",
          account_owner: null,
          amount: -500,
          authorized_date: null,
          category: ["Personal", "Sporting Goods"],
          category_id: "19046000",
          date: "2020-08-22",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Madison Bicycle Shop",
          name: "Madison Bicycle Shop",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "bdrdxWVzqySa347kpeWbiD9RnpBEZKcV5A3oW",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Shops", "Sporting Goods"],
          waiwai_categories: ["Personal", "Sporting Goods"],
        },
        {
          account_id: "A767nE3kmKu1nZQp93E4c4a5Qe67LaF17qo9j",
          account_owner: null,
          amount: -25,
          authorized_date: null,
          category: ["Debt", "Credit Card"],
          category_id: "16001000",
          date: "2020-08-13",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: null,
          name: "CREDIT CARD 3333 PAYMENT *//",
          payment_channel: "other",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "W6V6RDGy9ksGE5KDNaJvfDw8EZLRA3clre46d",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Payment", "Credit Card"],
          waiwai_categories: ["Debt", "Credit Card"],
        },
        {
          account_id: "W6V6RDGy9ksGE5KDNaJvfDwgK753ywflre46b",
          account_owner: null,
          amount: -5.4,
          authorized_date: null,
          category: ["Transportation", "Taxi"],
          category_id: "22016000",
          date: "2020-08-13",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Uber",
          name: "Uber 063015 SF**POOL**",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "LE6EVDZN9PFDq5pNemZ9s9N6r5BX81cPbZ9kq",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Travel", "Taxi"],
          waiwai_categories: ["Transportation", "Taxi"],
        },
        {
          account_id: "bdrdxWVzqySa347kpeWbiD9glX8KP9fV5A3me",
          account_owner: null,
          amount: -5850,
          authorized_date: null,
          category: ["Personal", "Debit"],
          category_id: "21006000",
          date: "2020-08-12",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: null,
          name: "ACH Electronic CreditGUSTO PAY 123456",
          payment_channel: "other",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: "ACH",
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "Rm6m8Dgy9GtL65P4xz8aiWkwJDz9jNTRKeGP3",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Transfer", "Debit"],
          waiwai_categories: ["Personal", "Debit"],
        },
        {
          account_id: "GLALQDPxmdsNx5R1qPaVFVyZ3omPQyu1lDn69",
          account_owner: null,
          amount: -1000,
          authorized_date: null,
          category: ["Income", "Deposit"],
          category_id: "21007000",
          date: "2020-08-12",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: null,
          name: "CD DEPOSIT .INITIAL.",
          payment_channel: "other",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "GLALQDPxmdsNx5R1qPaVFVy4gdl9aPC1lDn6D",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Transfer", "Deposit"],
          waiwai_categories: ["Income", "Deposit"],
        },
        {
          account_id: "nLeL5nVQjAsx6Kr9ZDWAiB7MPlyEZ7C6d1GAR",
          account_owner: null,
          amount: -78.5,
          authorized_date: null,
          category: ["Entertainment", "Gyms and Fitness Centers"],
          category_id: "17018000",
          date: "2020-08-11",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Touchstone",
          name: "Touchstone Climbing",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "93D38EnMZ6iWna15LyRwuwPZl6DJyLHRLdEq5",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Recreation", "Gyms and Fitness Centers"],
          waiwai_categories: ["Entertainment", "Gyms and Fitness Centers"],
        },
        {
          account_id: "W6V6RDGy9ksGE5KDNaJvfDwgK753ywflre46b",
          account_owner: null,
          amount: 500,
          authorized_date: null,
          category: ["Transportation", "Airlines and Aviation Services"],
          category_id: "22001000",
          date: "2020-08-11",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "United Airlines",
          name: "United Airlines",
          payment_channel: "other",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "poZo5nVReASedzBMjWbDf9KJpWejZ6cL4PKpX",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Travel", "Airlines and Aviation Services"],
          waiwai_categories: [
            "Transportation",
            "Airlines and Aviation Services",
          ],
        },
        {
          account_id: "W6V6RDGy9ksGE5KDNaJvfDwgK753ywflre46b",
          account_owner: null,
          amount: -12,
          authorized_date: null,
          category: ["Food", "Restaurants"],
          category_id: "13005032",
          date: "2020-08-10",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: "3322",
            zip: null,
          },
          merchant_name: "McDonald's",
          name: "McDonald's",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "opQp5nVm7yUowrAPe6L1iJBzXEWKd5cRa6KoA",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Food and Drink", "Restaurants", "Fast Food"],
          waiwai_categories: ["Food", "Restaurants"],
        },
        {
          account_id: "W6V6RDGy9ksGE5KDNaJvfDwgK753ywflre46b",
          account_owner: null,
          amount: -4.33,
          authorized_date: null,
          category: ["Food", "Restaurants"],
          category_id: "13005043",
          date: "2020-08-10",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Starbucks",
          name: "Starbucks",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "gjdjbWVa37UakeDMZPGbiEZ5ApLwoPfgbAMEd",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Food and Drink", "Restaurants", "Coffee Shop"],
          waiwai_categories: ["Food", "Restaurants"],
        },
        {
          account_id: "W6V6RDGy9ksGE5KDNaJvfDwgK753ywflre46b",
          account_owner: null,
          amount: -89.4,
          authorized_date: null,
          category: ["Food", "Restaurants"],
          category_id: "13005000",
          date: "2020-08-09",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Sparkfun",
          name: "SparkFun",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "8BABpEGjQZsRedykq8ZntlKzrB6aJAFwADrWE",
          transaction_type: "place",
          unofficial_currency_code: null,
          plaid_categories: ["Food and Drink", "Restaurants"],
          waiwai_categories: ["Food", "Restaurants"],
        },
        {
          account_id: "A767nE3kmKu1nZQp93E4c4a5Qe67LaF17qo9j",
          account_owner: null,
          amount: 4.22,
          authorized_date: null,
          category: ["Income", "Credit"],
          category_id: "21005000",
          date: "2020-08-08",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: null,
          name: "INTRST PYMNT",
          payment_channel: "other",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "A767nE3kmKu1nZQp93E4c4aDBmJMw7u17qo9n",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Transfer", "Credit"],
          waiwai_categories: ["Income", "Credit"],
        },
        {
          account_id: "nLeL5nVQjAsx6Kr9ZDWAiB7MPlyEZ7C6d1GAR",
          account_owner: null,
          amount: -500,
          authorized_date: null,
          category: ["Transportation", "Airlines and Aviation Services"],
          category_id: "22001000",
          date: "2020-07-29",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "United Airlines",
          name: "United Airlines",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "vGyGqnVWklTwX4RJ9pAkiD4oamXRMxcWjyXvB",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Travel", "Airlines and Aviation Services"],
          waiwai_categories: [
            "Transportation",
            "Airlines and Aviation Services",
          ],
        },
        {
          account_id: "W6V6RDGy9ksGE5KDNaJvfDwgK753ywflre46b",
          account_owner: null,
          amount: -6.33,
          authorized_date: null,
          category: ["Transportation", "Taxi"],
          category_id: "22016000",
          date: "2020-07-27",
          iso_currency_code: "USD",
          location: {
            address: null,
            city: null,
            lat: null,
            lon: null,
            state: null,
            store_number: null,
            zip: null,
          },
          merchant_name: "Uber",
          name: "Uber 072515 SF**POOL**",
          payment_channel: "in store",
          payment_meta: {
            by_order_of: null,
            payee: null,
            payer: null,
            payment_method: null,
            payment_processor: null,
            ppd_id: null,
            reason: null,
            reference_number: null,
          },
          pending: false,
          pending_transaction_id: null,
          transaction_id: "EMbM9D4B63iKn5wo9mJVCVgoJNnXBrCXwWE4v",
          transaction_type: "special",
          unofficial_currency_code: null,
          plaid_categories: ["Travel", "Taxi"],
          waiwai_categories: ["Transportation", "Taxi"],
        },
      ],
    },
  ],
  accountsLoading: false,
  transactionsLoading: false,
  userFirstVisit: false,
  incomeSum: 1008.44,
  paycheckSum: 0,
  otherIncomeSum: 1008.44,
  spendingSum: 22311.58,
  spendRangeDaysSelected: 30,
  totalTransactionCount: 34,
  reviewedTransactionCount: 0,
  categoriesThisSpendRange: [
    {
      x: 1,
      waiwaiName: "Housing",
      plaidName: "Housing",
      name: "Housing",
    },
    {
      x: 2,
      waiwaiName: "Transportation",
      plaidName: "Transportation",
      name: "Transportation",
    },
    {
      x: 3,
      waiwaiName: "Food",
      plaidName: "Food",
      name: "Food",
    },
    {
      x: 4,
      waiwaiName: "Utilities",
      plaidName: "Utilities",
      name: "Utilities",
    },
    {
      x: 5,
      waiwaiName: "Insurance & Healthcare",
      plaidName: "Insurance & Healthcare",
      name: "Insurance & Healthcare",
    },
    {
      x: 6,
      waiwaiName: "Debt",
      plaidName: "Debt",
      name: "Debt",
    },
    {
      x: 7,
      waiwaiName: "Personal",
      plaidName: "Personal",
      name: "Personal",
    },
    {
      x: 8,
      waiwaiName: "Education",
      plaidName: "Education",
      name: "Education",
    },
    {
      x: 9,
      waiwaiName: "Child Care",
      plaidName: "Child Care",
      name: "Child Care",
    },
    {
      x: 10,
      waiwaiName: "Entertainment",
      plaidName: "Recreation",
      name: "Entertainment",
    },
    {
      x: 11,
      waiwaiName: "Savings",
      plaidName: "Savings",
      name: "Savings",
    },
    {
      x: 12,
      waiwaiName: "Income",
      plaidName: "Income",
      name: "Income",
    },
  ],
  spendingByCategory: {
    Housing: 0,
    Transportation: 1036.12,
    Food: 2211.46,
    Utilities: 0,
    "Insurance & Healthcare": 0,
    Debt: 4207,
    Personal: 12700,
    Education: 0,
    "Child Care": 0,
    Entertainment: 157,
    Savings: 0,
    Income: 2000,
  },
  sortedCategoriesUnderBudget: [
    "Savings",
    "Utilities",
    "Insurance & Healthcare",
    "Education",
    "Child Care",
    "Housing",
  ],
  sortedCategoriesOverBudget: [
    "Transportation",
    "Food",
    "Debt",
    "Personal",
    "Income",
    "Entertainment",
  ],
};
